### PR TITLE
do everyone a favor

### PR DESCRIPTION
**Pull request by Jan200101**

### CODE REVIEW

**Comment by Jan200101** [comment]
If you are bored report the account for uploading copyrighted material to github

**Comment by GovanifY** [comment]
@Jan200101 dmca takedowns can only be sent by copyright holders, so there's nothing much to do there, apart trolling silica out of here

**Comment by Jan200101** [comment]
@GovanifY while yeah DMCA take downs can be only send by the copyright holder the account can still be reported for being a blatant throwaway used to without a doubt distribute copyrighted work

**Comment by GovanifY** [comment]
yeah true, don't think that'll do much since we're reporting on copyright grounds but eh

**Comment by TotallyTobyFox** [comment]
but why tho ? why take it down xD

**Comment by Xane123** [comment]
> but why tho ? why take it down xD

If someone compiles this, they basically get Undertale for free, which I doubt Toby Fox would like. However, as mentioned above, Toby himself would have to report this for it to get taken down.

In case that ever does happen, I've downloaded this just to look at things like the sprites and of course to have the game's version of CORE, the song I like.

**Pull request closed without merging**
